apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app: neo4j-standalone   
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 7474
      targetPort: 7474
    - protocol: TCP
      name: bolt
      port: 7687
      targetPort: 7687